# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpu-mock.fullname" . }}-config
  labels:
    {{- include "gpu-mock.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "gpu-mock.gpuConfig" . | nindent 4 }}
