# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpu-mock.fullname" . }}
  labels:
    {{- include "gpu-mock.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gpu-mock.fullname" . }}
  labels:
    {{- include "gpu-mock.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gpu-mock.fullname" . }}
  labels:
    {{- include "gpu-mock.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gpu-mock.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gpu-mock.fullname" . }}
    namespace: {{ .Release.Namespace }}
